apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: sample-nginx-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8081
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
